### ISSUE TITLE
Cannot use with tf.keras

### ISSUE THREAD

**Issue by CatEek** [qubvel/efficientnet#48]
Consistently getting errors, either `No module named 'efficientnet.tfkeras'` or `AttributeError: 'tuple' object has no attribute 'layer'`. Using with standalone Keras, model compiles ok, however, I want to use tf.data.
I'm using tensorflow-gpu==1.14

**Comment by qubvel** [comment]
Hi @CatEek , try to uninstall and install again:
```bash
$ pip uninstall efficientnet
$ pip install -U git+https://github.com/qubvel/efficientnet
```

**Comment by qubvel** [comment]
New version not in PyPI yet

**Comment by CatEek** [comment]
Hi @qubvel , thanks for quick response and for great lib! Unfortunately, nothing changes. I'm working in Pycharm, Updated pip to latest version, during installation I provided this option `-U git+https://github.com/qubvel/efficientnet`, but got same error `No module named 'efficientnet.tfkeras`. Should I try later, or is there anything I could be doing wrong? Thank you in advance!

**Comment by qubvel** [comment]
My be the problem in environment, check that you are using `python` and `pip` from the same "place"

**Comment by CatEek** [comment]
Actually, I was able to make it work. New version 1.0.0 became available in about a day after your answer. I mentioned, that network architecture differs slightly from previous version. Or am I getting something wrong?

**Comment by qubvel** [comment]
It differs in details of implementation, but during inference it produces same results and weights are compatible.

**Comment by PallawiSinghal** [comment]
> ```shell
> pip install -U git+https://github.com/qubvel/efficientnet
> ```

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/qubvel/efficientnet
  Cloning https://github.com/qubvel/efficientnet to /private/var/folders/lb/6vn29x116sj735zwzk5xmp1rdcvfm9/T/pip-req-build-OYSdW2
  Running command git clone -q https://github.com/qubvel/efficientnet /private/var/folders/lb/6vn29x116sj735zwzk5xmp1rdcvfm9/T/pip-req-build-OYSdW2
ERROR: Package 'efficientnet' requires a different Python: 2.7.16 not in '>=3.0.0'


I am getting this error can you please help.

**Comment by maheeetaaa** [comment]
@qubvel Hello, I am trying to follow the binary example you provided in the package, unfortunately I get the same error " No module named 'efficientnet.tfkeras'"

I am using colab.  I have already used " !git clone https://github.com/qubvel/efficientnet.git". On top of it I see that in the log it writes efficientnet 1.1.1 is installed but still does not change the results. vesion 1.0.0 also says that no module named efficientnet is available. 

I am also new to these topics so I am sorry if I am asking stupid questions :)
